nombre = "Emaster5528E@062005"
nombre_binario = ''.join(format(ord(caracter), '08b') for caracter in nombre)
print(nombre_binario)
nombre = "Emaster5528E@062005"
nombre_binario = ''.join(format(ord(caracter), '08b') for caracter in nombre)
print(nombre_binario)
nombre = "Emaster5528E@062005"
nombre_binario = ''.join(format(ord(caracter), '08b') for caracter in nombre)
print(nombre_binario)
nombre = "Emaster5528E@062005"
nombre_binario = ''.join(format(ord(caracter), '08b') for caracter in nombre)
print(nombre_binario)
nombre = "Emaster5528E@062005"
nombre_binario = ''.join(format(ord(caracter), '08b') for caracter in nombre)
print(nombre_binario)
nombre = "Emaster5528E@062005"
nombre_binario = ''.join(format(ord(caracter), '08b') for caracter in nombre)
print(nombre_binario)
nombre = "Emaster5528E@062005"
nombre_binario = ''.join(format(ord(caracter), '08b') for caracter in nombre)
print(nombre_binario)
nombre = "Emaster5528E@062005"
nombre_binario = ''.join(format(ord(caracter), '08b') for caracter in nombre)
print(nombre_binario)
nombre = "Emaster5528E@062005"
nombre_binario = ''.join(format(ord(caracter), '08b') for caracter in nombre)
print(nombre_binario)
nombre = "Emaster5528E@062005"
nombre_binario = ''.join(format(ord(caracter), '08b') for caracter in nombre)
print(nombre_binario)
nombre = "Emaster5528E@062005"
nombre_binario = ''.join(format(ord(caracter), '08b') for caracter in nombre)
print(nombre_binario)
nombre = "Emaster5528E@062005"
nombre_binario = ''.join(format(ord(caracter), '08b') for caracter in nombre)
print(nombre_binario)
nombre = "Emaster5528E@062005"
nombre_binario = ''.join(format(ord(caracter), '08b') for caracter in nombre)
print(nombre_binario)
nombre = "Emaster5528E@062005"
nombre_binario = ''.join(format(ord(caracter), '08b') for caracter in nombre)
print(nombre_binario)
nombre = "Emaster5528E@062005"
nombre_binario = ''.join(format(ord(caracter), '08b') for caracter in nombre)
print(nombre_binario)
nombre = "Emaster5528E@062005"
nombre_binario = ''.join(format(ord(caracter), '08b') for caracter in nombre)
print(nombre_binario)
nombre = "Emaster5528E@062005"
nombre_binario = ''.join(format(ord(caracter), '08b') for caracter in nombre)
print(nombre_binario)
nombre = "Emaster5528E@062005"
nombre_binario = ''.join(format(ord(caracter), '08b') for caracter in nombre)
print(nombre_binario)